Created check for updating an existing ro-crate and accompanying test…
ResearchObject/ro-crate-py pull request #88
Opened 2021-11-09 17:30 UTC by pauldg

Created a PR based on this issue https://github.com/ResearchObject/ro-crate-py/issues/86

2021-11-10 08:42 UTC, simleo requested changes

2021-11-10 08:42 UTC, simleo commented on rocrate/model/file.py
> +            if not os.path.exists(out_file_path) or not filecmp.cmp(self.source, out_file_path):
* `out_file_path` is a `Path`, so the check here can simply be `out_file_path.exists()`
* Why `filecmp`? The scenario is writing to the same location, so either the file does not exist (then we want to copy it) or it's the _same_ file as the source (then we don't want to copy it). If we also want to cater for a use case where the output crate directory is _different_ but already contains something, then we probably want to overwrite the existing contents, or raise an exception. Not to mention the fact that `filecmp` is likely to be much more expensive. So the check should be `if out_file_path.exists() and out_file_path.samefile(self.source)`
* This is not the only place in the code where a file is copied to the output location. For instance, there's the copy of unlisted files in [`ROCrate._copy_unlisted`](https://github.com/ResearchObject/ro-crate-py/blob/f4baf75095545d573f62ecf3ebeba511c80572e9/rocrate/rocrate.py#L456).

2021-11-10 08:42 UTC, simleo commented on test/test-data/read_write_crate/abstract_wf.cwl
> +class: Workflow
This directory is a copy of `read_crate`. This is not needed: every unit test gets its own copy of the whole test-data tree.

2021-11-10 08:42 UTC, simleo commented on test/test_readwrite.py
> +@pytest.mark.parametrize("gen_preview,to_zip,from_zip", [(False, False, False), (False, True, True), (True, False, False), (True, True, True)])
The `gen_preview` flag is immaterial for this specific test. `to_zip` and `from_zip` might matter in principle, but they don't with the current implementations (input: zip is extracted to a temp dir before reading; output: crate is written to a temp output dir before zipping). So this can be a non-parametrized test.

2021-11-10 08:42 UTC, simleo commented on test/test_readwrite.py
> +    out_path = tmpdir / 'read_write_crate'
This is not the same dir as the source (`crate_dir`), so this test is not actually testing the intended scenario.

2021-11-10 08:42 UTC, simleo commented on test/test_readwrite.py
> +    creator_id = '003'
No need to add contextual entities in this case. What matters is to check that the crate can be written back to the source location.

2021-11-10 15:57 UTC, pauldg commented on rocrate/model/file.py
> +            if not os.path.exists(out_file_path) or not filecmp.cmp(self.source, out_file_path):
Correct me if I'm wrong but the samefile check seems redundant here.

2021-11-11 11:16 UTC, simleo commented on rocrate/model/file.py
> +            if not os.path.exists(out_file_path) or not filecmp.cmp(self.source, out_file_path):
It's not redundant. If you just write this:

```python
if not out_file_path.exists():
    shutil.copy(self.source, out_file_path)
```

Then it's not possible to update the file from a different source. Consider the following scenario:

```python
import shutil
from rocrate.rocrate import ROCrate

shutil.rmtree("/tmp/crate")
shutil.copytree("test/test-data/read_crate", "/tmp/crate")
crate = ROCrate("/tmp/crate")
readme = crate.dereference("test_file_galaxy.txt")
with open(readme.source, "rt") as f:
    print(f.readline().strip())
new_source = "/tmp/foobar.txt"
with open(new_source, "wt") as f:
    f.write("FooBar\n")
crate.delete(readme)
crate.add_file(new_source, "test_file_galaxy.txt")
crate.write("/tmp/crate")
with open(readme.source, "rt") as f:
    print(f.readline().strip())
```

You can run the above program from the ro-crate-py root dir. The output is:

```
SRR10903401
SRR10903401
```

I.e., the file is **not** updated (the copy is silently ignored).

If you write this instead:

```python
if not out_file_path.exists() or not out_file_path.samefile(self.source):
    shutil.copy(self.source, out_file_path)
```

The output is:

```
SRR10903401
FooBar
```

I.e., the update is successful.

What we want to avoid is copying a file to itself, so in principle what's redundant is the other check, `out_file_path.exists()`. However, `samefile` raises an exception when `out_file_path` does not exist, so we need to add the check to avoid that.

2021-11-11 16:45 UTC, simleo commented
@pauldg please merge https://github.com/pauldg/ro-crate-py/pull/1. That will fix the PEP8 errors so we can run the CI workflow.

2021-11-11 16:59 UTC, merged